query getAmenities($queryParams: QueryFilterDto!) {
  getAmenities(queryParams: $queryParams) {
    meta {
      ...MetaFragment
    }
    items {
      id
      name
      isActive
      icon
      type
      isAppFilter
    }
  }
}
